### ISSUE TITLE
update dependancy to symfony 5

### ISSUE THREAD

**Issue by psohm** [nesk/rialto#24]
hello
you use symfony/process 3.3 or 4.0
but symfony 5 is out, can you update composer.json
Regards

**Comment by psohm** [comment]
https://github.com/nesk/rialto/pull/25

**Comment by willsmanley** [comment]
Something is wrong with your PR relating to travis, so I created a new PR that allows for symfony/process v5 support: [PR](https://github.com/nesk/rialto/pull/27)

**Comment by nesk** [comment]
Fixed in v1.4.0
