### ISSUE TITLE
Support async/await syntax in JS functions

### ISSUE THREAD

**Issue by nesk** [nesk/rialto#5]
Currently, it is impossible to use `await` in a JS function because the function isn't defined as `async`. Making all the JS functions async by default is not a good option because some Puppeteer's events could one day require a return value.

A good option would be to add a chaining method to return an async JS function:

```php
JsFunction::create("console.log(await 'Hello world!')")->async()
```

The above function creation would generate the following JS code:

```js
return async function () {
    var page = global.puphpeteerResources['a-unique-id-to-the-resource'];
    console.log(await page.content())
};
```

**Important:** the [documentation](https://github.com/nesk/rialto/blob/master/docs/api.md#javascript-functions) must be updated.

<hr>

[Method chaining](https://github.com/nesk/rialto/issues/4) should probably be implemented before dealing with this issue.

**Comment by JoelEinbinder** [comment]
It is extremely unlikely that puppeteer will require a return value for events. For the same reason as you, we wouldn’t want marking functions as async to drastically change the behavior.

**Comment by nesk** [comment]
Oh, that's some good news! However, I think I will stick with this approach since its closer to the way JS works (the fact that functions are sync by default).

Thank you for the info!
